#!/bin/zsh

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

WORDCHARS=${WORDCHARS/\/}

typeset -A ZINIT
ZINIT_HOME=$XDG_CACHE_HOME/zsh/zinit
ZINIT[HOME_DIR]=$ZINIT_HOME
ZINIT[ZCOMPDUMP_PATH]=$XDG_CACHE_HOME/zsh/zcompdump

if [[ ! -f $ZINIT_HOME/bin/zinit.zsh ]]; then
	git clone https://github.com/zdharma/zinit $ZINIT_HOME/bin
	zcompile $ZINIT_HOME/bin/zinit.zsh
fi
source $ZINIT_HOME/bin/zinit.zsh
load=light

HISTSIZE=2000000				# How many lines of history to keep in memory
HISTFILE=$XDG_CACHE_HOME/zsh/zsh_history	# Where to save history to disk
SAVEHIST=2000000				# Number of history entries to save to disk
setopt hist_ignore_all_dups 			# remove older duplicate entries from history
setopt hist_reduce_blanks   			# remove superfluous blanks from history items
setopt inc_append_history   			# save history entries as soon as they are entered
setopt share_history        			# share history between different instances of the shell

fpath=($ZDOTDIR/completion $fpath)

zinit $load willghatch/zsh-saneopt

zinit $load mafredri/zsh-async
zinit $load rupa/z
zinit $load sindresorhus/pure

zinit ice silent wait:1 atload:_zsh_autosuggest_start
zinit $load zsh-users/zsh-autosuggestions

zinit ice blockf; zplugin $load zsh-users/zsh-completions

zinit ice silent wait!1 atload"ZINIT[COMPINIT_OPTS]=-C; zpcompinit"
zinit $load zdharma/fast-syntax-highlighting

# zinit $load pradeepvrd/tmux-zsh-vim-titles

autoload -Uz compinit
compinit

zinit cdreplay -q

zstyle ':completion:*' menu select

setopt auto_list      # automatically list choices on ambiguous completion
setopt auto_menu      # automatically use menu completion
setopt always_to_end  # move cursor to end if word had one match

zstyle ':completion:*' menu select                                          # select completions with arrow keys
zstyle ':completion:*' group-name ''                                        # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

[ -e $HOME/.nix-profile/etc/profile.d/nix.sh ] && . $HOME/.nix-profile/etc/profile.d/nix.sh

if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
elif [ -d /usr/local/opt/fzf ]; then
  source /usr/local/opt/fzf/shell/key-bindings.zsh
  source /usr/local/opt/fzf/shell/completion.zsh
fi

if [ -n "${commands[virtualenvwrapper_lazy.sh]}" ]; then
  export WORKON_HOME=$XDG_DATA_HOME/virtualenvs
  source "$(which virtualenvwrapper_lazy.sh)"
fi

[ -n "${commands[direnv]}" ] && eval "$(direnv hook zsh)"

if [ -n "${commands[tmux]}" ] && [ -e $HOME/.config/tmux/tmux.conf ]; then
  alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'
fi

export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

export PATH=$HOME/bin:$PATH

[ -e "$ZDOTDIR/privaterc" ] && source "$ZDOTDIR/privaterc"

_exists() {
  type "$1" >/dev/null 2>&1
}

_exists nvim && alias dotedit="cd ~/stash/dotfiles && nvim ."

_exists loginctl && session_type="$(loginctl show-session "$XDG_SESSION_ID" -p Type --value)"
if [ "$session_type" = x11 ]; then
  _exists xclip && \
    alias copy="xclip -selection clipboard" && \
    alias paste="xclip -o -selection clipboard"
elif [ "$session_type" = wayland ]; then
  _exists wl-copy && alias copy="wl-copy"
  _exists wl-paste && alias paste="wl-paste"
fi

alias zsrc="source ${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/.zshrc"

export GOBIN=$HOME/go/bin
export PATH=$GOBIN:$PATH
export PATH="$HOME/.emacs.d/bin:$PATH"
