#!/bin/zsh

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

typeset -A ZPLGM
ZPLG_HOME=$XDG_CACHE_HOME/zsh/zplugin
ZPLGM[HOME_DIR]=$ZPLG_HOME
ZPLGM[ZCOMPDUMP_PATH]=$XDG_CACHE_HOME/zsh/zcompdump

if [[ ! -f $ZPLG_HOME/bin/zplugin.zsh ]]; then
	git clone https://github.com/psprint/zplugin $ZPLG_HOME/bin
	zcompile $ZPLG_HOME/bin/zplugin.zsh
fi
source $ZPLG_HOME/bin/zplugin.zsh
load=light

zplugin $load willghatch/zsh-saneopt

zplugin $load mafredri/zsh-async
zplugin $load rupa/z
zplugin $load sindresorhus/pure

zplugin ice silent wait:1 atload:_zsh_autosuggest_start
zplugin $load zsh-users/zsh-autosuggestions

zplugin ice blockf; zplugin $load zsh-users/zsh-completions

zplugin ice silent wait!1 atload"ZPLGM[COMPINIT_OPTS]=-C; zpcompinit"
zplugin $load zdharma/fast-syntax-highlighting

export ASDF_CONFIG_FILE=$XDG_CONFIG_HOME/asdf/asdfrc
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=$XDG_CONFIG_HOME/asdf/tool-versions
export ASDF_DATA_DIR=$XDG_DATA_HOME/asdf

. $XDG_DATA_HOME/asdf/asdf.sh
. $XDG_DATA_HOME/asdf/completions/asdf.bash

source $XDG_DATA_HOME/cargo/env
source /usr/share/doc/fzf/examples/key-bindings.zsh